"""Snapshot tests for daemon/post-review.sh's --dry-run payload.

Fixture is `tests/fixtures/post_review_snapshot/` and holds:
- anchored.json: 2 findings (single-line `important+bug`, range `nit+refactor`)
- unanchored.json: 1 finding (`pre_existing+polish`) routed to ## Additional findings
- summary.txt: review summary
- expected_payload.json: payload when no findings were dropped (default path)
- expected_payload_dropped_2.json: payload when 2 forbidden-combo findings were dropped

Snapshots store the banner/footer identity as `__PROJECT_NAME__` /
`__PROJECT_URL__` placeholders. The test normalizes the live-derived
identity into the same placeholders before comparing, so the snapshot
passes on the canonical clone and any fork alike. Identity itself is
covered by `test_footer_reflects_git_remote_identity`.

Regenerate snapshots (identity is normalized automatically — no manual
find/replace step):

    python tests/test_post_review.py
    python tests/test_post_review.py --dropped-combo 2

The `__main__` block at the bottom runs the daemon, applies `_strip_identity`
to the body, and writes the result to the matching `expected_payload*.json`.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE = REPO_ROOT / "tests" / "fixtures" / "post_review_snapshot"
DAEMON = REPO_ROOT / "daemon"


FIXTURE_HEAD_SHA = "0123456789abcdef0123456789abcdef01234567"


def _run_post_review(*extra_args: str, head_sha: str | None = FIXTURE_HEAD_SHA) -> dict:
    """Returns the full --dry-run object: {"review": <api-payload>,
    "mirror_comment": <PR-comment body for the #49 body-wipe backup>}."""
    args = [
        "bash",
        str(DAEMON / "post-review.sh"),
        "--owner",
        "example",
        "--repo",
        "example",
        "--number",
        "999",
        "--summary-file",
        str(FIXTURE / "summary.txt"),
        "--anchored",
        str(FIXTURE / "anchored.json"),
        "--unanchored",
        str(FIXTURE / "unanchored.json"),
    ]
    if head_sha is not None:
        args += ["--head-sha", head_sha]
    args += ["--dry-run", *extra_args]
    result = subprocess.run(args, capture_output=True, text=True, check=True)
    return json.loads(result.stdout)


def _git_remote_identity() -> tuple[str, str]:
    """Owner and repo derived from the local git origin — same parse the
    daemon does, used by the derive test to stay correct on any checkout."""
    url = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "remote", "get-url", "origin"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    match = re.search(r"github\.com[:/]([^/]+)/(.+?)(?:\.git)?$", url)
    assert match, f"unexpected git remote URL format: {url}"
    return match.group(1), match.group(2)


def _strip_identity(body: str) -> str:
    """Substitute the live-derived identity with the fixture's placeholders so
    the snapshot stays stable on canonical and fork checkouts alike. Anchored
    on the exact banner/footer templates emitted by post-review.sh."""
    owner, repo = _git_remote_identity()
    return body.replace(
        f"[{repo}](https://github.com/{owner}/{repo})",
        "[__PROJECT_NAME__](__PROJECT_URL__)",
    ).replace(
        f"_Generated by {repo} v",
        "_Generated by __PROJECT_NAME__ v",
    )


def test_dry_run_payload_matches_snapshot():
    actual = _run_post_review()["review"]
    actual["body"] = _strip_identity(actual["body"])
    expected = json.loads((FIXTURE / "expected_payload.json").read_text())
    assert actual == expected, (
        "post-review.sh --dry-run payload drifted from snapshot. "
        "Regenerate per the docstring if the change was intentional."
    )


def test_dry_run_payload_with_dropped_combo_matches_snapshot():
    # Locks in the ADR 0005 per-finding-failure rendering: an italic note sits
    # between the summary and `## Additional findings` so the operator sees the
    # redaction in the body itself, not just in stderr.
    actual = _run_post_review("--dropped-combo", "2")["review"]
    actual["body"] = _strip_identity(actual["body"])
    expected = json.loads((FIXTURE / "expected_payload_dropped_2.json").read_text())
    assert actual == expected, (
        "post-review.sh --dry-run --dropped-combo 2 payload drifted from snapshot. "
        "Regenerate per the docstring if the change was intentional."
    )


def test_mirror_comment_wraps_full_review_body_in_details():
    # #49 backup: the posted review body, verbatim, inside <details>.
    result = _run_post_review()
    mirror = result["mirror_comment"]
    assert mirror.startswith("<details>")
    assert "<summary>" in mirror
    assert mirror.rstrip().endswith("</details>")
    assert result["review"]["body"] in mirror


def test_mirror_comment_carries_sentinel_so_dedup_survives_body_wipe():
    # After a wipe this comment is the only surviving copy of the sha-sentinel.
    mirror = _run_post_review()["mirror_comment"]
    assert f"<!-- pr-review-agent:sha:{FIXTURE_HEAD_SHA} -->" in mirror


def test_sentinel_present_and_matches_adr_0006_format():
    # ADR 0006 fixes the sentinel format so the dedup migration parser in
    # `daemon/poll.sh` can grep it byte-exactly. Locks the regex separately
    # from the full-payload snapshot so a format regression points at this
    # test, not at a scrolling JSON diff.
    body = _run_post_review()["review"]["body"]
    match = re.search(r"<!-- pr-review-agent:sha:([0-9a-f]{40}) -->", body)
    assert match, "ADR 0006 sentinel missing from review body"
    assert match.group(1) == FIXTURE_HEAD_SHA
    # Sentinel sits below the operator footer so it parses out cleanly without
    # mid-body false positives.
    footer_idx = body.index("Submit, edit, or cancel as needed.")
    assert match.start() > footer_idx


def test_sentinel_omitted_when_head_sha_unset():
    # Dry-run / debug invocations may omit --head-sha. The script should emit
    # no sentinel rather than a malformed `pr-review-agent:sha:` with an empty
    # value the parser would never accept.
    body = _run_post_review(head_sha=None)["review"]["body"]
    assert "pr-review-agent:sha:" not in body


def test_own_pr_submits_comment_review():
    # ADR 0008: own PRs auto-submit a COMMENT review in the create POST itself,
    # via an `event` field. Others' PRs omit it and stay pending.
    review = _run_post_review("--own-pr")["review"]
    assert review.get("event") == "COMMENT"
    # Others' path (default) carries no event key — the review stays pending.
    assert "event" not in _run_post_review()["review"]


def test_own_pr_skips_body_wipe_mirror():
    # Own PRs never touch the submit modal, so there is no wipe to back up: the
    # mirror is reported as null rather than a redundant comment body.
    assert _run_post_review("--own-pr")["mirror_comment"] is None


def test_own_pr_footer_says_edit_or_delete_not_submit():
    # The review is already submitted, so the action line is post-hoc
    # (edit/delete), not the pre-submit submit/cancel of a pending review.
    body = _run_post_review("--own-pr")["review"]["body"]
    assert "Edit or delete as needed." in body
    assert "Submit, edit, or cancel as needed." not in body
    assert "🤖 Auto-submitted by" in body


def test_footer_reflects_git_remote_identity():
    # Zero-config path: the daemon parses the local git origin to fill the
    # footer/banner. Body must surface that derived identity. Test stays
    # correct on canonical and fork checkouts alike by querying git directly.
    owner, repo = _git_remote_identity()
    body = _run_post_review()["review"]["body"]
    assert f"[{repo}](https://github.com/{owner}/{repo})" in body


if __name__ == "__main__":
    import sys

    extra = sys.argv[1:]
    # Snapshot stays the bare review payload; the mirror_comment is structural
    # (asserted directly in tests) so it is not snapshotted.
    payload = _run_post_review(*extra)["review"]
    payload["body"] = _strip_identity(payload["body"])
    suffix = "_dropped_2" if "--dropped-combo" in extra else ""
    out = FIXTURE / f"expected_payload{suffix}.json"
    out.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
    print(f"regenerated {out.name}")
