#!/usr/bin/env bash
# post-review.sh — submit the assembled pending review to GitHub via gh api.

set -euo pipefail

# shellcheck source=daemon/lib.sh disable=SC1091
source "$(dirname "$0")/lib.sh"

DRY_RUN=0
HEAD_SHA=""
OWNER=""
REPO=""
NUMBER=""
SUMMARY_FILE=""
ANCHORED=""
UNANCHORED=""
DROPPED_COMBO=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --owner)
      OWNER="$2"
      shift 2
      ;;
    --repo)
      REPO="$2"
      shift 2
      ;;
    --number)
      NUMBER="$2"
      shift 2
      ;;
    --summary-file)
      SUMMARY_FILE="$2"
      shift 2
      ;;
    --anchored)
      ANCHORED="$2"
      shift 2
      ;;
    --unanchored)
      UNANCHORED="$2"
      shift 2
      ;;
    --head-sha)
      HEAD_SHA="$2"
      shift 2
      ;;
    --dropped-combo)
      DROPPED_COMBO="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    *)
      log_err "post-review.sh: unknown arg: $1"
      exit 1
      ;;
  esac
done

[[ -n "$OWNER" ]] || {
  log_err "missing --owner"
  exit 1
}
[[ -n "$REPO" ]] || {
  log_err "missing --repo"
  exit 1
}
[[ -n "$NUMBER" ]] || {
  log_err "missing --number"
  exit 1
}
[[ -n "$SUMMARY_FILE" ]] || {
  log_err "missing --summary-file"
  exit 1
}
[[ -n "$ANCHORED" ]] || {
  log_err "missing --anchored"
  exit 1
}
[[ -n "$UNANCHORED" ]] || {
  log_err "missing --unanchored"
  exit 1
}
if ! [[ "$DROPPED_COMBO" =~ ^[0-9]+$ ]]; then
  log_err "--dropped-combo must be a non-negative integer (got: $DROPPED_COMBO)"
  exit 1
fi

summary="$(cat "$SUMMARY_FILE")"

# Auto-prepend a preview-release banner while pyproject.toml's version stays on 0.x.x.
# Disappears automatically once the project ships a 1.0+ version.
banner=""
pyproject="$(dirname "$0")/../pyproject.toml"
if [[ -r "$pyproject" ]]; then
  version="$(sed -n 's/^version = "\(.*\)"/\1/p' "$pyproject" | head -1)"
  if [[ "$version" =~ ^0\. ]]; then
    banner="_Generated by pr-review-agent v${version} (preview release). Rendering, voice, anchoring, and failure handling are still landing in slices. See open issues for in-progress work._"$'\n\n---\n\n'
  fi
fi

# Per-finding degradation note (ADR 0005). Surfaces dropped findings so the
# operator sees the redaction in the body rather than only in stderr logs.
dropped_note=""
if [[ "$DROPPED_COMBO" -gt 0 ]]; then
  noun="findings"
  if [[ "$DROPPED_COMBO" -eq 1 ]]; then noun="finding"; fi
  dropped_note=$'\n\n'"_${DROPPED_COMBO} ${noun} dropped (forbidden severity×type combo)._"
fi

# Review-body footer per ADR 0001 D3. Hardcoded project URL; forks change this
# one constant. The leading `\n\n---\n\n` detaches the footer from whatever
# ends the body (summary, dropped-note, `## Additional findings`, or nothing).
footer=$'\n\n---\n\n🤖 Drafted by [pr-review-agent](https://github.com/taewanu/pr-review-agent). Submit, edit, or cancel as needed.'

# Render unanchored findings into a Markdown section appended to the review body.
# `## Additional findings` is the canonical relocation surface per ADR 0005.
# Severity → emoji map per ADR 0002 (same map inlined in inline-comments jq below).
additional="$(jq -r '
  if length == 0 then ""
  else "\n\n## Additional findings\n\n" + (
    map(
      "- `" + .path + ":" + (.line | tostring) +
      (if .end_line and .end_line != .line then "-" + (.end_line | tostring) else "" end) +
      "` " +
      ({"important": "🔴", "nit": "🟡", "pre_existing": "🟣"}[.severity] // "❓") +
      " **" + .type + "**\n\n  " + .body
    ) | join("\n\n")
  )
  end
' "$UNANCHORED")"

body_with_additional="${banner}${summary}${dropped_note}${additional}${footer}"

# Build inline comment payloads. Range findings (end_line > line) use
# {start_line, start_side, line, side, body}; single-line uses {line, side, body}.
# Inline body format per ADR 0002: severity emoji + bold type label + body + AI-drafted footer.
comments_json="$(jq '
  map(
    {
      path: .path,
      side: "RIGHT",
      body: (
        ({"important": "🔴", "nit": "🟡", "pre_existing": "🟣"}[.severity] // "❓") +
        " **" + .type + "**\n\n" + .body +
        "\n\n---\n\n🤖 _AI-drafted_"
      )
    }
    + (
      if .end_line and .end_line > .line then
        {start_line: .line, start_side: "RIGHT", line: .end_line}
      else
        {line: .line}
      end
    )
  )
' "$ANCHORED")"

payload="$(jq -n \
  --arg body "$body_with_additional" \
  --argjson comments "$comments_json" \
  --arg commit_id "$HEAD_SHA" \
  '{
    body: $body,
    comments: $comments
  } + (if $commit_id == "" then {} else {commit_id: $commit_id} end)')"

if [[ $DRY_RUN -eq 1 ]]; then
  printf '%s\n' "$payload"
  exit 0
fi

log_info "posting Pending review to ${OWNER}/${REPO}#${NUMBER}"

# Capture both streams: gh api writes the 422 response body to stdout and a
# short status line to stderr. The pending-conflict marker is in the response
# body, so stderr-only capture misses it. Per ADR 0005 we don't auto-cancel
# (would destroy the operator's in-flight draft).
out_file="$(mktemp -t pr-review-post.XXXXXX)"
trap 'rm -f "$out_file"' EXIT

if printf '%s' "$payload" | gh api \
  --method POST \
  "repos/${OWNER}/${REPO}/pulls/${NUMBER}/reviews" \
  --input - >"$out_file" 2>&1; then
  cat "$out_file"
  exit 0
fi

if grep -q "User can only have one pending review per pull request" "$out_file"; then
  printf 'category=pending-conflict\n' >&2
else
  printf 'category=post-failed\n' >&2
fi
cat "$out_file" >&2
exit 1
